version: "3"

services:
  nfldb:
    image: postgres:9.6-alpine
    container_name: nfldb
    ports:
     - "5432:5432"
    tty: true
    environment:
     - POSTGRES_PASSWORD=pass
  api:
    build: api
    container_name: nflapi
    depends_on:
      - nfldb
    ports:
     - "5000:5000"
    links:
     - nfldb
    environment:
     - POSTGRES_SERVER=nfldb
     - POSTGRES_PORT=5432
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=pass