FROM python:2.7.13-alpine3.6

COPY ./app/* /app/
WORKDIR /app

RUN pip install virtualenv
RUN mkdir ~/.virtual
RUN virtualenv ~/.virtual/nflapi
RUN source ~/.virtual/nflapi/bin/activate

RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev
RUN pip install -r requirements.txt

ENV POSTGRES_SERVER localhost
ENV POSTGRES_PORT 5432
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD pass

ENTRYPOINT ["python"]
CMD ["app.py"]